controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

velocity_controller:
  ros__parameters:
    joints:
      - rueda_derecha
      - rueda_izquierda

diff_drive_base_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    use_stamped_vel: false
    right_wheel_names: ["rueda_derecha"]
    left_wheel_names: ["rueda_izquierda"]
    wheel_separation: 0.46
    wheel_radius: 0.085
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    publish_rate: 25.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    cmd_vel_timeout: 0.25
    base_frame_id: dummy_root
    enable_odom_tf: true
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 1.0
        has_jerk_limits: false
        max_jerk: 5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 6.0
        has_jerk_limits: false
        max_jerk: 10.47
